[package]
name = "gravity_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core async runtime
tokio = { version = "1.0", features = ["full"] }
actix = "0.13"

# Ethereum interaction
alloy = { version = "=1.0", features = ["full", "rlp", "hyper", "rpc", "rpc-types-json", "json-rpc"] }

# Serialization & Config
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# CLI & Logging
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
comfy-table = "7.1"

# Utilities
uuid = { version = "1.0", features = ["v4"] }
anyhow = "1.0"
thiserror = "1.0"
bytes = "1.0"
tokio-util = "0.7"

# HTTP client for RPC
reqwest = { version = "0.12", features = ["json", "http2"] }

# Random number generation
rand = "0.8"

# Async semaphore and synchronization
tokio-stream = "0.1"

# Additional dependencies for Stage 1
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
tempfile = "3.8"
url = "2.4"
dotenvy = "0.15.7"
async-trait = "0.1.88"
rayon = "1.10.0"
tower = "0.5.2"
crossbeam = "0.8.4"
dashmap = "6.1.0"
